# Generated by Django 4.0 on 2021-12-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=30)),
                ('college_name', models.CharField(default='', max_length=100)),
                ('course', models.CharField(default='', max_length=100)),
                ('phone', models.IntegerField(max_length=20)),
            ],
        ),
    ]
