# Generated by Django 4.0 on 2021-12-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Details',
        ),
    ]
