# Generated by Django 4.0 on 2021-12-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_student_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
    ]
