# Generated by Django 4.0 on 2021-12-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_details_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='phone',
            field=models.BigIntegerField(default=''),
        ),
    ]
