# Generated by Django 4.0 on 2021-12-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_details_email_alter_details_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='college_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='details',
            name='course',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='details',
            name='email',
            field=models.EmailField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='details',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='details',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='details',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
    ]
